### ISSUE TITLE
Allow years beyond 2014 in nflvid-footage & download-all-pbp-xml

### ISSUE THREAD

**Issue by jmatheson** [BurntSushi/nflvid#16]
nflvid-footage should be updated to allow years beyond 2014. Possibly check datestamp of today and allow years through current.

**Comment by jmatheson** [comment]
it also seems that the slicer is having issues. it is trying to pull http://e2.cdnl3.neulion.com/nfl/edl/nflgr/2015/56503.xml but gives a 404

**Comment by jmatheson** [comment]
download-all-pbp-xml  is also throwing 404s for 2015

**Comment by BurntSushi** [comment]
My suspicion is that `nflvid` is busted because the CDN is busted. But I'd be otherwise happy to accept a patch that fixes things. :-)

**Comment by jmatheson** [comment]
Yea, i figured that was the case. It seems to have worked for the game downloads. I will dig in a bit and let you know what I find.

**Comment by jmatheson** [comment]
fixed with https://github.com/BurntSushi/nflvid/pull/17
