### ISSUE TITLE
Superbowl coaches film not working?

### ISSUE THREAD

**Issue by AndrewRook** [BurntSushi/nflvid#18]
First off, this and nflgame are awesome packages, thanks for putting them together!

Anyway, I'm trying to download footage of last year's super bowl. The download itself finishes without complaint and the resulting file size of the download seems reasonable (~5.4 MB for the dry run), but I can't get the file to open. The command I'm using is this:
```
$ nflvid-footage --season 2014 --teams SEA --season-type POST --weeks 5 --dry-run ./
```
Meanwhile, downloading the NFC championship game works:
```
$ nflvid-footage --season 2014 --teams SEA --season-type POST --weeks 3 --dry-run ./
```
so I would assume it's not a problem with my personal installation. I did a dry run download of the two prior super bowls and got the same result. I see that [you've run into this issue with broadcast footage of super bowls](https://github.com/BurntSushi/nflvid/issues/5#issuecomment-23937578), but I was hoping that the coaches' film would be ok. Any advice on this? Or is it just a known issue with the content provider?

**Comment by BurntSushi** [comment]
I really don't know and I probably won't personally dig into this problem. I think you're on your own unfortunately.

It might be worth trying more games. It's possible there is an outlier that is corrupt or something...

**Comment by AndrewRook** [comment]
Yeah, I figured as much but it didn't hurt to ask. I checked three super bowls with no luck, and I really need last year's footage so I can't just substitute another game.

I'm poking around a little bit on my own and I've got a couple leads, but I'm really not a video expert so we'll see how far I get. I'll close this issue for now; if I make any good progress I can always reopen it.
