### ISSUE TITLE
Coaches tapes for preseason?

### ISSUE THREAD

**Issue by queuebit** [BurntSushi/nflvid#20]
I noticed the note with preseason games for broadcast, 

> Note that it is unlikely any URL returned will be valid for preseason or postseason games.

but I wasn't sure if you had ever gotten preseason games working for coaches tapes.

Making requests for den preseason 2015:

`nflvid-footage --season 2015 --teams den --season-type PRE -- /path/to/full`

seems to prompt asking to download the correct games, but then fails with `rtmpdump`:

```
These are the games that match your search criteria:
(Season: 2015, Week: 1, DEN at SEA)
(Season: 2015, Week: 2, DEN at HOU)
(Season: 2015, Week: 3, SF at DEN)
(Season: 2015, Week: 4, ARI at DEN)
Are you sure you want to start downloading? [y/n] y
Downloading game 2015082256 (Season: 2015, Week: 2, DEN at HOU)
 Downloading game 2015081456 (Season: 2015, Week: 1, DEN at SEA)
Could not run 'rtmpdump --rtmp rtmp://neulionms.fcod.llnwd.net --app a5306/e1 --playpath mp4:u/nfl/nfl/coachtapes/2015/56785_all_1600 --timeout 10 -o /path/to/full/2015082256.mp4' (exit code 1):
   RTMPDump v2.4
   (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
   WARNING: No application or playpath in URL!
   Connecting ...
   INFO: Connected...
   ERROR: Closing connection: NetStream.Play.StreamNotFound
```

Much thanks for creating the tool. 👍

**Comment by BurntSushi** [comment]
I don't know, sorry. You'll have to debug this on your own. I'd suggest trying to re-create the download using `rtmpdump` manually and debug from there.

**Comment by queuebit** [comment]
Yep, starting down that path. Thanks!

**Comment by queuebit** [comment]
> Coaches film is not available during the Preseason.
> &mdash; http://www.nfl.com/coachesfilm

closing.
