### ISSUE TITLE
Question: Seasons '11 - '15 Only?

### ISSUE THREAD

**Issue by jrunrun** [BurntSushi/nflvid#27]
Hey thanks for the help on the last issue. I just tried to download 2017, doesn't look like that is available; feedback from the client is pasted below.

usage: nflvid-footage [-h] [--threads THREADS]
                      [--season {2011,2012,2013,2014,2015}]
                      [--weeks WEEKS [WEEKS ...]] [--teams TEAMS [TEAMS ...]]
                      [--season-type {PRE,REG,POST}] [--dry-run] [--progress]
                      [--files] [--broadcast] [--condensed]
                      [--quality {400,800,1200,1600,2400,3000,4500}]
                      [--show-url] [--show-dead] [--no-confirm]
                      footage_dir

Can you confirm?

Assuming this is true, do you happen to know where one could find current 2017 games?

Thanks in advance!

**Comment by BurntSushi** [comment]
I updated the README today: https://github.com/BurntSushi/nflvid/blob/master/README.md --- In particular:

> This project is unmaintained. The code may still be useful and parts of it may still work, but you're on your own.

In particular, the commit prior to that README update was almost two years ago, and the last serious development was three years ago.

I don't use this tool any more. You're on your own. Sorry.
